version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/backend-coding-test

    steps:
      - checkout
      - run: sudo apt-get update 
      - run: sudo apt-get upgrade
      - run: npm install
      - run: npm test